customhost = "database-1.cpz7zg34rcbs.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "desmondchongsonchuen-employee"
customregion = "us-east-1"
